export const Category = {
  CREATE: 'CATEGORY_CREATE',
  UPDATE: 'CATEGORY_UPDATE',
  DELETE: 'CATEGORY_DELETE',
};

export const Expense = {
  CREATE: 'EXPENSE_CREATE',
  UPDATE: 'EXPENSE_UPDATE',
  DELETE: 'EXPENSE_DELETE',
};
